const TOTAL_TILES = 108;
const ROW_SIZE = 12;
const TILE_INITIAL_POSITION = 0;
const NUMBER_TO_SUB_FOR_CONVERT_NUMBER_TO_INDEX = 1;
const INITIAL_PRICE = 0;
const TILE_DELETE_COUNT = 1;

module.exports = {
  TOTAL_TILES,
  ROW_SIZE,
  TILE_INITIAL_POSITION,
  NUMBER_TO_SUB_FOR_CONVERT_NUMBER_TO_INDEX,
  INITIAL_PRICE,
  TILE_DELETE_COUNT
};
